name: TinySettings
version: '${project.version}'
main: me.pondhalf.project.tinySettings.TinySettings
api-version: '1.21'
softdepend: [PlaceholderAPI]
commands:
  tinysettings:
    description: Open the settings GUI
    usage: /tinysettings [reload]
permissions:
  tinysettings.use:
    default: true
  tinysettings.reload:
    default: op
